### DISCUSSION TITLE
Error while show dbs command

### DISCUSSION THREAD

**Discussion by genexus007** [FerretDB/FerretDB#4977] [General]
Today, I restored my MongoDB dump into FerretDB using the production Docker setup. One of my databases is approximately 450GB. When I run the show dbs; command, I encounter a MongoServerError[InternalError]: integer out of range error. Any idea what might be causing this?
logs:

```
2025-03-24T15:46:42.784Z	ERROR	documentdb_api/documentdb_api.go:375	Query	{"args":{"0":"RawDocument<75>"},"error":"ERROR: integer out of range (SQLSTATE 22003)","name":"pool","pid":5570,"sql":"SELECT list_databases::bytea FROM documentdb_api.list_databases($1::bytea)","time":294298800}
2025-03-24T15:46:42.784Z	ERROR+1	mongoerrors/mongoerrors.go:148	Unmapped error code	{"arg":"documentdb_api.list_databases","error":"&pgconn.PgError{Severity:\"ERROR\", SeverityUnlocalized:\"ERROR\", Code:\"22003\", Message:\"integer out of range\", Detail:\"\", Hint:\"\", Position:0, InternalPosition:0, InternalQuery:\"\", Where:\"SQL statement \\\"WITH r1 AS (SELECT DISTINCT database_name AS name , 0::int8 AS \\\"sizeOnDisk\\\", false AS empty FROM documentdb_api_catalog.collections),r2 AS (SELECT documentdb_core.row_get_bson(r1) AS document FROM r1),r3 AS (SELECT document FROM r2 ),r4 AS (SELECT COALESCE(documentdb_api_catalog.bson_array_agg(r3.document, ''), '{ \\\"\\\": [] }') AS databases,[pg_catalog.pg](http://pg_catalog.pg/)_database_size(pg_catalog.current_database())::int4 AS \\\"totalSize\\\",  1.0::float8 AS ok FROM r3)SELECT documentdb_core.row_get_bson(r4) AS document FROM r4\\\"\", SchemaName:\"\", TableName:\"\", ColumnName:\"\", DataTypeName:\"\", ConstraintName:\"\", File:\"int8.c\", Line:1254, Routine:\"int84\"}","name":"handler"}
2025-03-24T15:46:42.785Z	WARN	clientconn/conn.go:623	Response header: length:   109, id:    5, response_to:   24, opcode: OP_MSG	{"name":"listener"}
2025-03-24T15:46:42.785Z	WARN	clientconn/conn.go:624	Response message:
{
  `FlagBits`: `[]`,
  `Checksum`: int64(0),
  `Sections`: [
    {
      `Kind`: 0,
      `Document`: {
        `ok`: 0.0,
        `errmsg`: `integer out of range`,
        `code`: 1,
        `codeName`: `InternalError`,
      },
    },
  ],
}	{"name":"listener"}
```

**Comment by AlekSi** [comment]
Let’s start by successfully setting up MongoDB and FerretDB in `diff-normal` mode: https://docs.ferretdb.io/migration/premigration-testing/

Please restore dump into both FerretDB and MongoDB, start FerretDB in diff-proxy mode, connect with `mongosh`, issue `show dbs` command, and provide the **full** log output of FerretDB.

**Reply by shivananda-shiragavi** [reply]
Do we need to start mongodb also? 
Below is my docker-compose.yml

```
services:
  postgres:
    image: ghcr.io/ferretdb/postgres-documentdb:17-0.102.0-ferretdb-2.0.0
    platform: linux/amd64
    restart: on-failure
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - ferretdb_net

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:2.0.0
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://user:password@postgres:5432/postgres
      - FERRETDB_PROXY_ADDR=diff-normal
    depends_on:
      - postgres
    networks:
      - ferretdb_net

networks:
  ferretdb_net:
    name: ferretdb
```
