### DISCUSSION TITLE
Restoring large collection is way to slow

### DISCUSSION THREAD

**Discussion by shivananda-shiragavi** [FerretDB/FerretDB#4985] [General]
I am restoring two large collection in my db which is around 112 and 123 GB. It's almost now 24hr but still this restore is 40% completed. Belos is the command which I am using to restore:
`mongorestore --uri="mongodb://user_name:password@127.0.0.1/" > /data/.ferretdb/restore_logs/res.log 2>&1`
is there any way to improve this restore.
Whereas in mongodb restoreing same collection used to take around 5hrs.

**Comment by ptrfarkas** [comment]
Hi @shivananda-shiragavi 

Thank you for trying FerretDB.

Can you please advise on your environment? Are you using FerretDB with one of our Docker images? If yes, which image did you pull?
If not, can you be more specific on your method of deployment?  Appreciate in advance.

**Reply by shivananda-shiragavi** [reply]
Thanks for replying @ptrfarkas!
I am using Ubuntu server, and using FerretDB production image ghcr.io/ferretdb/ferretdb:2.0.0.
I am using docker-compose.yml.
below is content of it:

```
services:
  postgres:
    image: ghcr.io/ferretdb/postgres-documentdb:17-0.102.0-ferretdb-2.0.0  
    platform: linux/amd64
    restart: on-failure
    environment:
      - POSTGRES_USER=user_name
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - ferretdb_net

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:2.0.0
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://user_name:password@postgres:5432/postgres
    depends_on:
      - postgres
    networks:
      - ferretdb_net
    deploy:
      resources:
        limits:
          memory: 32g
          cpus: '16'


networks:
  ferretdb_net:
    name: ferretdb
```
