### DISCUSSION TITLE
Seeking a minimal Docker image alternative to ghcr.io/ferretdb/postgres-documentdb

### DISCUSSION THREAD

**Discussion by unclesmiley** [FerretDB/FerretDB#5149] [General]
Hello,

I'm currently using FerretDB with PostgreSQL following the setup guide from the official documentation (https://docs.ferretdb.io/installation/ferretdb/docker/#run-production-image). While the solution works great, I've noticed that the `ghcr.io/ferretdb/postgres-documentdb` image is quite large in size.

**Current Setup:**
```yaml
services:
  postgres:
    image: ghcr.io/ferretdb/postgres-documentdb:17-0.102.0-ferretdb-2.1.0
    platform: linux/amd64
    restart: on-failure
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./data:/var/lib/postgresql/data

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:2.1.0
    restart: on-failure
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://username:password@postgres:5432/postgres
      - FERRETDB_AUTH=false
```

**Questions:**
1. Are there any lightweight alternatives to `ghcr.io/ferretdb/postgres-documentdb`?
2. Would it be possible to use a bare PostgreSQL image with some additional configurations to achieve the same functionality?
3. What's the minimum required setup to get MongoDB protocol support with PostgreSQL?

Any suggestions or guidance would be greatly appreciated. Thank you!
