### ISSUE TITLE
"ghcr.io/ferretdb/ferretdb:1.23.0" is not work

### ISSUE THREAD

**Issue by yingshaoxo** [FerretDB/FerretDB#4513]
### FerretDB version

1.23.0

### Backend

sqlite3

### Environment

- OS:docker
- Deployment:
- Deployment details:

### What did you do?

docker-compose file:
```
version: "3.9"

services:
  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:1.23.0
    network_mode: "host"        
    environment:
      - FERRETDB_HANDLER=sqlite
      - FERRETDB_SQLITE_URL=file:/data/
    volumes:
      - ./configs/ferretdb_data:/data/
    restart: always
```

I use "mongodb://yingshaoxo:yingshaoxo@127.0.0.1:27017/?authMechanism=PLAIN" to do operations with pymongo

### What did you expect to see?

I should see it is working normal.

### What did you see instead?

But I see bugs here:

```
[msg_update.go:135 handler.(*Handler).updateDocument] [update.go:114 common.UpdateDocument] [collection.go:191 sqlite.(*collection).UpdateAll] [collection.go:177 sqlite.(*collection).UpdateAll.func1] attempt to write a readonly database (8), full error: {'ok': 0.0, 'errmsg': '[msg_update.go:135 handler.(*Handler).updateDocument] [update.go:114 common.UpdateDocument] [collection.go:191 sqlite.(*collection).UpdateAll] [collection.go:177 sqlite.(*collection).UpdateAll.func1] attempt to write a readonly database (8)', 'code': 1, 'codeName': 'InternalError'}
```

or

```
ferretdb_1  | 2024-08-06T07:03:45.919Z  WARN    clientconn/conn.go:641  Response message:
ferretdb_1  | {
ferretdb_1  |   "FlagBits": "[]",
ferretdb_1  |   "Checksum": int64(0),
ferretdb_1  |   "Sections": [
ferretdb_1  |     {
ferretdb_1  |       "Kind": 0,
ferretdb_1  |       "Document": {
ferretdb_1  |         "ok": 0.0,
ferretdb_1  |         "errmsg": "[msg_update.go:135 handler.(*Handler).updateDocument] [update.go:114 common.UpdateDocument] [collection.go:191 sqlite.(*collection).UpdateAll] [collection.go:177 sqlite.(*collection).UpdateAll.func1] attempt to write a readonly database (8)",
ferretdb_1  |         "code": 1,
ferretdb_1  |         "codeName": "InternalError",
ferretdb_1  |       },
ferretdb_1  |     },
ferretdb_1  |   ],
ferretdb_1  | }
```

**This bug is extreamely obvious when the sqlite3 data folder is empty at the beginning, when you want to create a database or add data to it by using mongodb command**

___

I also found if I use `image: ghcr.io/ferretdb/ferretdb:1.23.0`, everything works again.

```
version: "3.9"

services:
  ferretdb:
    # ./ferretdb-linux-amd64 --sqlite-url="file:data/"
    image: ghcr.io/ferretdb/all-in-one:1.23.0
    network_mode: "host"        
    environment:
      - FERRETDB_HANDLER=sqlite
      - FERRETDB_SQLITE_URL=file:/data/
    volumes:
      - ./configs/ferretdb_data:/data/
    restart: always
```
