### ISSUE TITLE
Postgres version

### ISSUE THREAD

**Issue by leteaaDEV** [FerretDB/FerretDB#4613]
### What should be done?

Hey I had Updates my ferret docker And it also Updated the postgres Version to latest (ig) I had to manuell set it back to 16.. 

### Where?

Dicker yml

### Definition of Done

- handler updated;
- all backends updated;
- unit tests added/updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- user documentation updated or an issue to create documentation created;
- something else?

**Comment by AlekSi** [comment]
Sorry, I don't understand what you did, what happened, and what you expected instead.

**Comment by leteaaDEV** [comment]
So.
1. i did `docker compose pull` und ferretdb.
2. i restarted ferrteddb
3. postgres updated to latest
4. i got a ferret error that postgres uses XX version and not 16.x
5. i had to set postgres to `image: postgres:16` in order to get it running again.

It would be helpful to find in the docs which version you should use exactly?

**Comment by AlekSi** [comment]
PostgreSQL does not automatically update itself – you updated the image by using `docker compose pull` for `postgres:latest`.

What error you've got from FerretDB? Please provide the full log output.

**Comment by leteaaDEV** [comment]
I dont have the logs anymore ready to provide.
I had the docker compose file stock on `image: postgres` :

```
services:
  postgres:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ferretdb
    volumes:
      - ./data:/var/lib/postgresql/data

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://postgres:5432/ferretdb

networks:
  default:
    name: ferretdb
```
that caused the error on update.
