### ISSUE TITLE
Validator not applied to collection

### ISSUE THREAD

**Issue by EnriqueL8** [FerretDB/FerretDB#5064]
### FerretDB, PostgreSQL, and DocumentDB versions

FerretDB version 2.1 and using the docker compose from the docs.

I'm trying to create a collection with a json schema validator but when I use mongosh it doesn't seem to be set. 

Snippet of Golang code
```golang
	jsonSchema := bson.M{
		"bsonType": "object",
		"required": []string{"name", "age"},
		"properties": bson.M{
			"name": bson.M{
				"bsonType": "string",
				"description": "the name of the user, which is required and " +
					"must be a string",
			},
			"age": bson.M{
				"bsonType": "int",
				"minimum":  18,
				"description": "the age of the user, which is required and " +
					"must be an integer >= 18",
			},
		},
	}
	validator := &bson.M{
		"$jsonSchema": jsonSchema,
	}

       opts := options.CreateCollection().SetValidator(validator)
	err := db.CreateCollection(ctx, "users", opts)
```

### Environment

- **OS**: Mac
- **Deployment**: Docker Compose

`docker-compose.yml`
```yaml
version: '3.8'

services:
  postgres:
    image: ghcr.io/ferretdb/postgres-documentdb:17-0.102.0-ferretdb-2.1.0
    platform: linux/amd64
    restart: on-failure
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - POSTGRES_LOG_STATEMENT=all 
    volumes:
      - ./data:/var/lib/postgresql/data

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:2.1.0
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://username:password@postgres:5432/postgres
      - FERRETDB_LOG_LEVEL=debug

networks:
  default:
    name: ferretdb
```

### What did you do?

Added above

### What did you expect to see?

I expected to see the validator added under options when querying `db.getCollectionInfos( { name: "users" } )`

### What did you see instead?

Empty options
