### ISSUE TITLE
v2.3.1 returns `fe_sendauth: no password supplied` while v2.1.0 works when used with the demo cloudnative-pg setup on kubernetes

### ISSUE THREAD

**Issue by fhoekstra** [FerretDB/FerretDB#5284]
### FerretDB, PostgreSQL, and DocumentDB versions

I couldn't find serverStatus, how about this?
```json
{
  "ferretdb": {"image": "ghcr.io/ferretdb/ferretdb:2.3.1"}
  "postgres": {"image": "ghcr.io/ferretdb/postgres-documentdb:17-0.104.0-ferretdb-2.3.1"}}
  "context": {"repo": "https://github.com/fhoekstra/home-ops/blob/main/kubernetes/apps/database/cloudnative-pg/app/ferretdb.yaml"}}
}
```

### Environment

- **OS**: Talos Linux
- **Deployment**: Kubernetes using cloudnative-pg
- **Deployment details**: Followed the instructions on https://blog.ferretdb.io/run-ferretdb-postgres-documentdb-extension-cnpg-kubernetes/ , this works with the older versions in the blog but not with these newer 2.3.1 images.

### What did you do?

Follow https://blog.ferretdb.io/run-ferretdb-postgres-documentdb-extension-cnpg-kubernetes/

But use the latest image tags instead: ghcr.io/ferretdb/ferretdb:2.3.1 and ghcr.io/ferretdb/postgres-documentdb:17-0.104.0-ferretdb-2.3.1

### What did you expect to see?

```
{
  acknowledged: true,
  insertedId: ObjectId('6859968c4e9f445c4fd72ecd')
}
```

### What did you see instead?

`MongoServerError[InternalError]: fe_sendauth: no password supplied`

**Comment by chilagrow** [comment]
Thanks for reporting this, let us look into it. I did reproduce this scenario with the mentioned versions `ghcr.io/ferretdb/ferretdb:2.3.1` and `ghcr.io/ferretdb/postgres-documentdb:17-0.104.0-ferretdb-2.3.1`.

The releases before `ghcr.io/ferretdb/ferretdb:2.2.0` and `ghcr.io/ferretdb/postgres-documentdb:17-0.103.0-ferretdb-2.2.0` doesn't have this issue, so the most recent release is impacted by this 🙏

**Comment by fhoekstra** [comment]
Thanks for the quick help and for selecting this issue for the board!

As per [the issue you linked](https://github.com/FerretDB/FerretDB/issues/5278#issuecomment-2995587600), adding the following [spec.postgresql.pg_hba section](https://cloudnative-pg.io/documentation/current/postgresql_conf/#the-pg_hba-section) resolved the issue:
```diff
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
[...]
spec:
  [...]
  postgresql:
    shared_preload_libraries:
      - pg_cron
      - pg_documentdb_core
      - pg_documentdb
    parameters:
      cron.database_name: 'postgres'
+   pg_hba:
+     - host postgres postgres 127.0.0.1/32 trust
  bootstrap:
    initdb:
      postInitSQL:
        - 'CREATE EXTENSION IF NOT EXISTS documentdb CASCADE;'
```

Hope this helps!
I also ran into another permission-related problem with this setup: (occurs in 2.1 and 2.3 equally) when trying to add WAL archiving: `"permission denied for schema documentdb_core"` I'll make a separate issue or PR for that once I've done some more debugging there.

**Comment by tholinka** [comment]
Can confirm the `pg_hba` field fixes this. The documentation / blog posts should be updated to include it.

@fhoekstra did you find a solution for the `permission denied for schema documentdb_core`? My replica instance is getting that message.

**Comment by fhoekstra** [comment]
Not yet, I had to set up a FoundryVTT instance with web GUI file access for a friend first, which turned into a bit of a yak with an entire auth stack. I'm planning to look at it this week before Froscon. Will update you with findings when I get to it

**Comment by mhkarimi1383** [comment]
I have manually ran this

```sql
GRANT ALL ON SCHEMA documentdb_api TO streaming_replica;
GRANT ALL ON SCHEMA documentdb_api_catalog TO streaming_replica;
GRANT ALL ON SCHEMA documentdb_api_internal TO streaming_replica;
GRANT ALL ON SCHEMA documentdb_core TO streaming_replica;
GRANT ALL ON SCHEMA documentdb_data TO streaming_replica;
```

I no error for now
We should check what is the correct permission for that

**Comment by mhkarimi1383** [comment]
I was not able to to do this via postInitSQL, since it will create `streaming_replica` user after running `postInitSQL`

we need a custom job that runs them after cluster startup

**Comment by eaglesemanation** [comment]
Been struggling a bunch with CNPG managed Postgres instance and FerretDB working together while not using superuser access, but it seems like I finally got it working. Here is my setup:
```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/imagecatalog_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: documentdb-postgres
  namespace: ferretdb
spec:
  images:
    - major: 17
      image: ghcr.io/ferretdb/postgres-documentdb:17-0.106.0-ferretdb-2.5.0
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ferretdb-pg
  namespace: ferretdb
spec:
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: documentdb-postgres
    major: 17
  storage:
    storageClass: whatever-you-use
    size: 10Gi
  # Needed to make postgres-documentdb run at all, thank this comment for figuring this out:
  # https://github.com/FerretDB/FerretDB/issues/4765#issuecomment-2701765707
  postgresUID: 999
  postgresGID: 999
  postgresql:
    shared_preload_libraries:
      - pg_cron
      - pg_documentdb_core
      - pg_documentdb
    parameters:
      # Got this from pg_cron docs
      cron.database_name: ferretDB
      # Copied from https://github.com/FerretDB/documentdb/blob/ferretdb/packaging/10-preload.sh
      documentdb.enableCompact: "true"
      documentdb.enableLetAndCollationForQueryMatch: "true"
      documentdb.enableNowSystemVariable: "true"
      documentdb.enableSortbyIdPushDownToPrimaryKey: "true"
      documentdb.enableSchemaValidation: "true"
      documentdb.enableBypassDocumentValidation: "true"
      documentdb.enableUserCrud: "true"
      documentdb.maxUserLimit: "100"
    pg_hba:
      # Fix for pg_cron, seems like it always runs from postgres user
      - host ferretDB postgres localhost trust
      # Fix FerretDB fe_sendauth error
      - host ferretDB ferret localhost trust
  bootstrap:
    initdb:
      database: ferretDB
      owner: ferret
      postInitApplicationSQL:
        - create extension if not exists pg_cron;
        - create extension if not exists documentdb cascade;
        # Instead of doing a bunch of grants on different schemas you can just grant an included role
        - grant documentdb_admin_role to ferret;
```

On FerretDB side I just use `uri` from auto-generated `ferretdb-pg-app` secret.
